// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_add
double rcpp_add(Rcpp::NumericVector v);
RcppExport SEXP _copykatcpp_rcpp_add(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add(v));
    return rcpp_result_gen;
END_RCPP
}
// apply_cpp_col
Rcpp::NumericVector apply_cpp_col(Rcpp::NumericMatrix x);
RcppExport SEXP _copykatcpp_apply_cpp_col(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cpp_col(x));
    return rcpp_result_gen;
END_RCPP
}
// apply_cpp_row_der
Rcpp::NumericVector apply_cpp_row_der(Rcpp::NumericMatrix x);
RcppExport SEXP _copykatcpp_apply_cpp_row_der(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cpp_row_der(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_sum
double rcpp_sum(Rcpp::NumericVector v);
RcppExport SEXP _copykatcpp_rcpp_sum(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_sum(v));
    return rcpp_result_gen;
END_RCPP
}
// apply_cpp_col_norm
Rcpp::DataFrame apply_cpp_col_norm(Rcpp::NumericMatrix x);
RcppExport SEXP _copykatcpp_apply_cpp_col_norm(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cpp_col_norm(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_med
double cpp_med(Rcpp::NumericVector x);
RcppExport SEXP _copykatcpp_cpp_med(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_med(x));
    return rcpp_result_gen;
END_RCPP
}
// apply_cpp_row_basel
Rcpp::NumericVector apply_cpp_row_basel(Rcpp::NumericMatrix x);
RcppExport SEXP _copykatcpp_apply_cpp_row_basel(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cpp_row_basel(x));
    return rcpp_result_gen;
END_RCPP
}
// apply_cpp_row_DR2
Rcpp::NumericVector apply_cpp_row_DR2(Rcpp::NumericMatrix x);
RcppExport SEXP _copykatcpp_apply_cpp_row_DR2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cpp_row_DR2(x));
    return rcpp_result_gen;
END_RCPP
}
// apply_cpp_row_temp
Rcpp::NumericVector apply_cpp_row_temp(Rcpp::NumericMatrix x);
RcppExport SEXP _copykatcpp_apply_cpp_row_temp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cpp_row_temp(x));
    return rcpp_result_gen;
END_RCPP
}
// apply_cpp_row_cfh
Rcpp::NumericVector apply_cpp_row_cfh(Rcpp::NumericMatrix x);
RcppExport SEXP _copykatcpp_apply_cpp_row_cfh(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cpp_row_cfh(x));
    return rcpp_result_gen;
END_RCPP
}
// apply_cpp_row_base
Rcpp::NumericVector apply_cpp_row_base(Rcpp::NumericMatrix x);
RcppExport SEXP _copykatcpp_apply_cpp_row_base(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cpp_row_base(x));
    return rcpp_result_gen;
END_RCPP
}
// apply_cpp_col_tempa
Rcpp::NumericVector apply_cpp_col_tempa(Rcpp::NumericMatrix x);
RcppExport SEXP _copykatcpp_apply_cpp_col_tempa(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cpp_col_tempa(x));
    return rcpp_result_gen;
END_RCPP
}
// apply_cpp_col_aj
Rcpp::NumericVector apply_cpp_col_aj(Rcpp::NumericMatrix x);
RcppExport SEXP _copykatcpp_apply_cpp_col_aj(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_cpp_col_aj(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_copykatcpp_rcpp_add", (DL_FUNC) &_copykatcpp_rcpp_add, 1},
    {"_copykatcpp_apply_cpp_col", (DL_FUNC) &_copykatcpp_apply_cpp_col, 1},
    {"_copykatcpp_apply_cpp_row_der", (DL_FUNC) &_copykatcpp_apply_cpp_row_der, 1},
    {"_copykatcpp_rcpp_sum", (DL_FUNC) &_copykatcpp_rcpp_sum, 1},
    {"_copykatcpp_apply_cpp_col_norm", (DL_FUNC) &_copykatcpp_apply_cpp_col_norm, 1},
    {"_copykatcpp_cpp_med", (DL_FUNC) &_copykatcpp_cpp_med, 1},
    {"_copykatcpp_apply_cpp_row_basel", (DL_FUNC) &_copykatcpp_apply_cpp_row_basel, 1},
    {"_copykatcpp_apply_cpp_row_DR2", (DL_FUNC) &_copykatcpp_apply_cpp_row_DR2, 1},
    {"_copykatcpp_apply_cpp_row_temp", (DL_FUNC) &_copykatcpp_apply_cpp_row_temp, 1},
    {"_copykatcpp_apply_cpp_row_cfh", (DL_FUNC) &_copykatcpp_apply_cpp_row_cfh, 1},
    {"_copykatcpp_apply_cpp_row_base", (DL_FUNC) &_copykatcpp_apply_cpp_row_base, 1},
    {"_copykatcpp_apply_cpp_col_tempa", (DL_FUNC) &_copykatcpp_apply_cpp_col_tempa, 1},
    {"_copykatcpp_apply_cpp_col_aj", (DL_FUNC) &_copykatcpp_apply_cpp_col_aj, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_copykatcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
