# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_add <- function(v) {
    .Call('_copykatcpp_rcpp_add', PACKAGE = 'copykatcpp', v)
}

apply_cpp_col <- function(x) {
    .Call('_copykatcpp_apply_cpp_col', PACKAGE = 'copykatcpp', x)
}

apply_cpp_row_der <- function(x) {
    .Call('_copykatcpp_apply_cpp_row_der', PACKAGE = 'copykatcpp', x)
}

rcpp_sum <- function(v) {
    .Call('_copykatcpp_rcpp_sum', PACKAGE = 'copykatcpp', v)
}

apply_cpp_col_norm <- function(x) {
    .Call('_copykatcpp_apply_cpp_col_norm', PACKAGE = 'copykatcpp', x)
}

cpp_med <- function(x) {
    .Call('_copykatcpp_cpp_med', PACKAGE = 'copykatcpp', x)
}

apply_cpp_row_basel <- function(x) {
    .Call('_copykatcpp_apply_cpp_row_basel', PACKAGE = 'copykatcpp', x)
}

apply_cpp_row_DR2 <- function(x) {
    .Call('_copykatcpp_apply_cpp_row_DR2', PACKAGE = 'copykatcpp', x)
}

apply_cpp_row_temp <- function(x) {
    .Call('_copykatcpp_apply_cpp_row_temp', PACKAGE = 'copykatcpp', x)
}

apply_cpp_row_cfh <- function(x) {
    .Call('_copykatcpp_apply_cpp_row_cfh', PACKAGE = 'copykatcpp', x)
}

apply_cpp_row_base <- function(x) {
    .Call('_copykatcpp_apply_cpp_row_base', PACKAGE = 'copykatcpp', x)
}

apply_cpp_col_tempa <- function(x) {
    .Call('_copykatcpp_apply_cpp_col_tempa', PACKAGE = 'copykatcpp', x)
}

apply_cpp_col_aj <- function(x) {
    .Call('_copykatcpp_apply_cpp_col_aj', PACKAGE = 'copykatcpp', x)
}

